#ifndef RTW_HEADER_dVOC_monitor_network1_acc_types_h_
#define RTW_HEADER_dVOC_monitor_network1_acc_types_h_
typedef struct P_Subsystempi2delay_dVOC_monitor_network1_T_
P_Subsystempi2delay_dVOC_monitor_network1_T ; typedef struct
P_Subsystem1_dVOC_monitor_network1_T_ P_Subsystem1_dVOC_monitor_network1_T ;
typedef struct P_Subsystempi2delay_dVOC_monitor_network1_g_T_
P_Subsystempi2delay_dVOC_monitor_network1_g_T ; typedef struct
P_Subsystem1_dVOC_monitor_network1_a_T_
P_Subsystem1_dVOC_monitor_network1_a_T ; typedef struct
P_AutomaticGainControl_dVOC_monitor_network1_T_
P_AutomaticGainControl_dVOC_monitor_network1_T ; typedef struct
P_dVOC_monitor_network1_T_ P_dVOC_monitor_network1_T ;
#endif
